# Generated by Django 2.1.15 on 2020-03-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200302_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Disponibles'), (2, 'No Disponible')], null=True),
        ),
    ]
