# Generated by Django 2.1.15 on 2020-03-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200303_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opciones',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='respuesta',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='pregunta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Opciones',
        ),
    ]
